{{- if .Values.pingKeys -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crond-agent.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crond-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $uuid := .Values.pingKeys }}
  {{ $name }}: {{ $uuid | quote }}
  {{- end }}
{{- end -}}
